// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhWA68mF_C1vMvNBX-GgNyDdRxf71w_vc',
    appId: '1:1063498395257:web:4afd04826362b37dedaea8',
    messagingSenderId: '1063498395257',
    projectId: 'boom-boom-7e000',
    authDomain: 'boom-boom-7e000.firebaseapp.com',
    storageBucket: 'boom-boom-7e000.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-hBkUXFAQnPqDkbGosNORwsR9VHR1Ejs',
    appId: '1:1063498395257:android:46aa10c35dc918adedaea8',
    messagingSenderId: '1063498395257',
    projectId: 'boom-boom-7e000',
    storageBucket: 'boom-boom-7e000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-0qLCPvpDWdZR4IY_PCHW5DVTfwbeUrE',
    appId: '1:1063498395257:ios:9e6c142de63b373aedaea8',
    messagingSenderId: '1063498395257',
    projectId: 'boom-boom-7e000',
    storageBucket: 'boom-boom-7e000.appspot.com',
    iosClientId: '1063498395257-or6q45nf2c6ine5us0ohedtfpmemb12c.apps.googleusercontent.com',
    iosBundleId: 'com.example.boomBoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-0qLCPvpDWdZR4IY_PCHW5DVTfwbeUrE',
    appId: '1:1063498395257:ios:9e6c142de63b373aedaea8',
    messagingSenderId: '1063498395257',
    projectId: 'boom-boom-7e000',
    storageBucket: 'boom-boom-7e000.appspot.com',
    iosClientId: '1063498395257-or6q45nf2c6ine5us0ohedtfpmemb12c.apps.googleusercontent.com',
    iosBundleId: 'com.example.boomBoom',
  );
}
